- hosts: localhost 
  gather_facts: no  
  vars_files:
    - ./vars/osx-config.yml
    - ./vars/personal.yml
    - ./vars/apps.yml
  tasks:
    - include_tasks: 
        file: tasks/node-setup.yml
        apply:
          tags: 
            - node
      tags: 
        - node
    - include_tasks: 
        file: tasks/zsh-setup.yml
        apply:
          tags: 
            - zsh 
      tags: 
        - zsh 
    - include_tasks: 
        file: tasks/nvim-setup.yml
        apply:
          tags: 
            - nvim 
      tags: 
        - nvim 
    - include_tasks: 
        file: tasks/tmux-setup.yml
        apply:
          tags: 
            - tmux 
      tags: 
        - tmux
    - include_tasks: 
        file: tasks/dotfiles.yml
        apply:
          tags: 
            - dotfiles 
      tags: 
        - dotfiles
    - include_tasks: 
        file: tasks/macos.yml
        apply:
          tags: 
            - macos 
      tags: 
        - macos
      
