- hosts: localhost 
  gather_facts: no  
  vars_files:
    - ./vars/personal.yml
    - ./vars/osx-config.yml
    - ./vars/apps-config.yml
  tasks:
    - include_tasks: 
        file: tasks/node-setup.yml
        apply:
          tags: 
            - node
      tags: 
        - node
    - include_tasks: 
        file: tasks/terminal-setup.yml
        apply:
          tags: 
            - terminal 
      tags: 
        - terminal 
    - include_tasks: 
        file: tasks/nvim-setup.yml
        apply:
          tags: 
            - nvim 
      tags: 
        - nvim 
    - include_tasks: 
        file: tasks/dotfiles.yml
        apply:
          tags: 
            - dotfiles 
      tags: 
        - dotfiles
    - include_tasks: 
        file: tasks/macos.yml
        apply:
          tags: 
            - macos 
      tags: 
        - macos
    - include_tasks: 
        file: tasks/apps.yml
        apply:
          tags: 
            - apps 
      tags: 
        - apps

