- name: Install homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
    update_homebrew: yes

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_cask_packages + profile_cask_packages | default([]) }}"

- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"
