- name: Put display to sleep after 15 minutes and computer to sleep after 30 minutes
  ansible.builtin.shell: pmset displaysleep 15 && pmset sleep 30
  changed_when: false
  become: true
- name: Set macOS default settings
  community.general.osx_defaults:
    domain: "{{ item['domain'] }}"
    key: "{{ item['key'] }}"
    type: "{{ item['type'] | default(omit) }}"
    value: "{{ item['value'] }}"
  loop: "{{ osxConfig }}"
  tags: system_settings