- name: Install tmux
  homebrew:
    name: tmux
- name: Clone TPM repository
  git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  become: true
  become_user: "{{ user_name }}"